[package]
name = "server"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
tokio = { workspace = true }
tonic = { workspace = true }
prost = { workspace = true }
clap = { workspace = true }

[build-dependencies]
tonic-build = "0.12"